# Use root/example as user/password credentials
version: "3.1"
services:
  MongoDB:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    restart: always

volumes:
  mongodb_data_container:
