version: "3.1"

services:
  main:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - my-datavolume-main:/var/lib/mysql

  replica-1:
    image: mariadb:10.3
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - my-datavolume-replica-1:/var/lib/mysql

  replica-2:
    image: mariadb:10.3
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - my-datavolume-replica-2:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  my-datavolume:
  my-datavolume-main:
  my-datavolume-replica-1:
  my-datavolume-replica-2:
